makecode:
  target: arcade
  platform: codal
  home_url: https://arcade.makecode.com/
theme: jekyll-theme-slate
include: 
  - assets
  - pics
  - README.md
defaults:
  - scope:
      path: "pics"
    values:
      image: true
